// DO NOT EDIT THIS FILE
// IT IS AUTO GENERATED BY ANGULAR-CLI
import {AddRoot} from './add/add-root.component';
import {DashboardRoot} from './dashboard/dashboard-root.component';

export const CliRouteConfig = [
  {path: '/add/...', name: 'AddRoot', component: AddRoot},
{path: '/dashboard/...', name: 'DashboardRoot', component: DashboardRoot},
];